included:
  - shotshot

excluded:
  - shotshot/Resources

line_length:
  warning: 200
  error: 300

file_length:
  warning: 1000
  error: 1500

function_body_length:
  warning: 100
  error: 200

type_body_length:
  warning: 600
  error: 1000

cyclomatic_complexity:
  warning: 20
  error: 30

function_parameter_count:
  warning: 8
  error: 12

identifier_name:
  min_length: 1
  max_length: 60

disabled_rules:
  - multiple_closures_with_trailing_closure
